### ISSUE TITLE
Week 2: Git Strategy

### ISSUE THREAD

**Issue by MelvinIdema** [MelvinIdema/blok-tech#1]
Implement your git strategy. How are you going to write commit messages? Are you going to make branches? Are you going to use issues or projects? Don't forget to document your research and final strategy to your wiki. Start using the command line to version control your matching-application. Just see how you like it and what the benefits are to using Git on the terminal. You can always switch back to version control trough your editor or a GUI.

### Todo:
- [X] Udemy Git & Github Bootcamp Course
- [X] Summarize Git & Github Bootcamp Course
- [X] Write about Git(hub) Strategy

### References:
[Git and Github Bootcamp](https://www.udemy.com/course/git-and-github-bootcamp/)
[Git from the bottom up](https://jwiegley.github.io/git-from-the-bottom-up/)
[Build your own Git](https://kushagra.dev/blog/build-git-learn-git/)
[How to write Git Commit Messages](https://chris.beams.io/posts/git-commit/)
