### ISSUE TITLE
Week 2: Building

### ISSUE THREAD

**Issue by MelvinIdema** [MelvinIdema/blok-tech#2]
Based on the concept, job story, requirement list and wireframe from the previous week start building out the front-end of the feature you are going to make for the matching-application. You can build the interface with the templating engine as you learned in back-end as opposed to 'plain' HTML & CSS.

### Todo
- [X] Turn your wireframe into HTML pages. Do a HTML breakdown of your wireframe and use semantic HTML as learned in previous courses.
- [X] Add presentational CSS to set-up some basic style. Think about colors, fonts, lay-out, responsiveness.
- [X] Add interaction and states, make sure it feels like an actual webpage. Add states to interactive elements, maybe add some animations and transitions.

Don't forget to think about the flow of your application (zero states, happy flow, error states). Do you need multiple pages?

### References
[📱 Het Concept](https://github.com/MelvinIdema/blok-tech/wiki/%F0%9F%93%B1--Het-Concept)
