### ISSUE TITLE
Week 3: Input

### ISSUE THREAD

**Issue by MelvinIdema** [MelvinIdema/blok-tech#3]
> Receive input from users on the server and manipulate that data for your own feature using HTTP request methods.

### Todo
- [x] Receive data from the user
- [x] Manipulate the data 
- [x] Store the data in a JSON file (for now)
- [x] Inject data dynamically into page
