### ISSUE TITLE
Week 3: Local

### ISSUE THREAD

**Issue by MelvinIdema** [MelvinIdema/blok-tech#5]
> Research and update your personal development setup to optimize your workflow

**Research the world of development tooling, and document the research in your wiki. Look into the following subjects, and describe why you think it's useful (or not) and if/how you're using it in your own work:**

### Todo
- [x] Text Editors Themes (f.e. [color themes](https://code.visualstudio.com/docs/getstarted/themes), [fonts](https://github.com/cmda-bt/pt-course-21-22/blob/main/fonts))
- [x] Text Editor Settings (f.e. [settings.json](https://code.visualstudio.com/docs/getstarted/settings))
- [x] Text Editors Extensions (f.e. [extensions marketplace](https://marketplace.visualstudio.com/))
- [x] CLI's and configurations (f.e. [prompts](https://github.com/denysdovhan/spaceship-prompt), [aliases](http://zsh.sourceforge.net/Intro/intro_8.html), [colors](https://osxdaily.com/2013/02/05/improve-terminal-appearance-mac-os-x/))
- [ ] Optional: Many developers create a repo with what are known as dotfiles. An export of all their configuration files. You can try to set-up your own if you feel a bit adventurous. Here are two examples from [Mathias](https://github.com/mathiasbynens/dotfiles) and [Danny](https://github.com/dandevri/dotfil.es).
