### ISSUE TITLE
PT-Week 4: Refactor

### ISSUE THREAD

**Issue by MelvinIdema** [MelvinIdema/blok-tech#9]
>The code you write will be executed by computers, but it will exclusively be read by humans. Therefore, it's critical that your code is easy to read, understand, and "mentally parse". Go back into your work so far and make sure that everything you've done so far is easy to understand for "outsiders" to your project.

## Todo:
- [x] Pick (minimum) 5 of the Clean Code JavaScript concepts
    - [x] Document what you refactored with before and after code blocks in your wiki.
- [x] Tweak or set-up additional linters

## Resources:
https://stackoverflow.com/questions/5778245/expressjs-how-to-structure-an-application
https://github.com/abdulmoiz251/node-express-rest-api-boilerplate
https://laravel.com/docs/9.x/controllers
https://softwareengineering.stackexchange.com/questions/255636/how-to-determine-what-should-get-its-own-respective-controller
https://www.patterns.dev/posts/classic-design-patterns/#detailmvc
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes
